### PR TITLE
[Merged by Bors] - Fix failing ldap test

### PR DESCRIPTION
**Pull request by sbernauer**
# Description

During resolving conflicts between #407 and #408 this line was not removed, thus creating (and overwriting!) the truststore *after* the ldap tls cert was added. Result was the ldap tls cert missing from the truststore

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by sbernauer** [comment]
Started test https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/druid-operator-it-custom/93/

**Review by razvan — APPROVED** [review]

**Comment by sbernauer** [comment]
Started new run https://ci.stackable.tech/job/druid-operator-it-custom/94/

**Comment by sbernauer** [comment]
Next run https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/druid-operator-it-custom/95/

**Comment by sbernauer** [comment]
Somehow hdfs did not start up. I think it's not related to the problem we are trying to solve.
Retriggered https://ci.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/druid-operator-it-custom/96/

**Comment by sbernauer** [comment]
@razvan Tests passed, can you please have another look?

**Pull request closed without merging**
