### PR TITLE
Discovery

### PR DESCRIPTION
**Pull request by fhennig**
## Description

- Added discovery to druid: The SQL connect string is written to a config map
- Fixed the role services - they were referencing a port by name that doesn't have that name anymore

## Review Checklist
- [x] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
LGTM.

**Comment by fhennig** [comment]
bors merge

**Comment by fhennig** [comment]
bors merge

**Comment by fhennig** [comment]
bors merge

**Pull request merged**
