### PR TITLE
[Merged by Bors] - Update to latest stackable images

### PR DESCRIPTION
**Pull request by maltesander**
# Description

- Updated all product / tools images to the latest stackable image version
- Retired support for druid 0.22.1 since it is not build with docker images anymore

**DO NOT MERGE BEFORE RELEASE IS DONE!**

## Review Checklist

- [ ] Code contains useful comments
- [ ] CRD change approved (or not applicable)
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
- [ ] Helm chart can be installed and deployed operator works (or not applicable)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by Maleware — CHANGES_REQUESTED** [review]
In https://github.com/stackabletech/druid-operator/blob/main/examples/psql/psql-hdfs-druid-cluster.yaml
- line 7 update Zookeeper from `3.5.8-stackable0.7.0` to  `3.5.8-stackable0.8.0`
- line 38 update hdfs from `3.3.3-stackable0.1.0` to `3.3.4-stackable0.2.0`

**Review by Maleware — CHANGES_REQUESTED** [review]
In https://github.com/stackabletech/druid-operator/blob/547d3b654445993cd050d358e7a9019605d351ca/examples/psql-s3/psql-s3-druid-cluster.yaml#L7 update zk from `3.5.8-stackable0.7.0` to `3.5.8-stackable0.8.0`

**Comment by maltesander** [comment]
> In https://github.com/stackabletech/druid-operator/blob/main/examples/psql/psql-hdfs-druid-cluster.yaml
> 
>     * line 7 update Zookeeper from `3.5.8-stackable0.7.0` to  `3.5.8-stackable0.8.0`
> 
>     * line 38 update hdfs from `3.3.3-stackable0.1.0` to `3.3.4-stackable0.2.0`

Thanks. Done https://github.com/stackabletech/druid-operator/pull/339/commits/108c59c46c8112b442ec5c39a7ff1f92afb5e7d3

**Review by Maleware — APPROVED** [review]
LGTM

**Comment by maltesander** [comment]
bors merge

**Pull request closed without merging**
