### PR TITLE
S3 integration

### PR DESCRIPTION
**Pull request by fhennig**
## Description

This PR makes it possible to use S3 as a deep storage backend, as well as ingesting data from S3.

The S3 extension needs to be loaded. It is now loaded by default, always.

A new property `s3` is added to the CRD:

    s3:
      endpoint: <custom s3 endpoint>
      credentialsSecret: <name of the secret containing the access key id and secret access key>

Just this allows to ingest data from buckets accessible with the given credentials.

The deep storage for s3 can be configured like so:
  
    s3:
      endpoint: s3-de-central.profitbricks.com
      credentialsSecret: s3-credentials
    deepStorage:
      storageType: s3
      bucket: druid-deepstorage
      baseKey: storage

TODO:
- [x] update documentation
- [x] update examples

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

### CODE REVIEW

**Review by maltesander — DISMISSED** [review]
LGTM.

**Comment by fhennig** [comment]
actually, wait a second, I'll remove the Hdfs thing from the enum entirely

**Review by maltesander — DISMISSED** [review]
LGTM.

**Review by maltesander — APPROVED** [review]
LGTM.

**Pull request merged**
